runtipi/runtipi

.github/workflows/ci.yml, packages/system-api/__mocks__/fs-extra.ts, packages/system-api/src/modules/apps/__tests__/apps.factory.ts, packages/system-api/src/modules/apps/__tests__/apps.service.test.ts, packages/system-api/src/modules/apps/apps.service.ts, packages/system-api/src/modules/apps/apps.types.ts, packages/system-api/src/modules/fs/__tests__/fs.helpers.test.ts, packages/system-api/src/modules/fs/fs.helpers.ts, scripts/unsafe-cleanup.sh
If an app gets installed insure that any existing folder in apps gets deleted. This will prevent the
user from getting in a limbo if an installation fails and the files are copied already
=> feat: cleanup folder before install

scripts/configure.sh, scripts/start.sh
Check if JQ is installed.
If it's not, try and install it.
Closes #169
=> Install jq if it's missing

scripts/configure.sh
Validated installing both Docker and jq without issues on the latest Pop_OS LTS.
Closes #185
=> Add support for Pop_OS to configure/start scripts

scripts/system-info.sh
MEM_TOTAL_BYTES not found for other system languages
like this
=> fix: Incorrect memory variables

.gitignore, scripts/configure.sh
On my Raspberry Pi 2 Model B running Raspbian 11, docker-compose failed to install as the binary does not exist at the specified URL. This commit hard-codes an update to the architecture specifically to be passed to the docker-compose URL for the correct installation of docker-compose. Additionally, it adds a check that a docker-compose command can be successfully executed, specifically retrieving the version, as the binary will exist after successful retrieval but will not do the correct thing.
```
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums" …
```
=> Fix installation of docker-compose on armv7l

scripts/app.sh, scripts/configure.sh, scripts/start.sh, scripts/stop.sh
Migrates all Docker Compose commands to the new Docker Compose plugin and ensures it is installed and up to date at each run of start.sh.
This should reduce support tickets around old Docker versions/old Docker Compose versions, and will automatically upgrade anyone still running old versions the next time they run start.sh.
=> Fully migrate to Docker Compose plugin

scripts/start.sh, scripts/stop.sh
Fixing two minor issues I had using start and stop scripts
* Now checks if the current working directory is `runtipi` and makes sure the referenced script (scripts/start.sh) exists. Before, you had to run the script using `sudo ./scripts/start.sh` exactly like that. Running `sudo scripts/start.sh` (note the missing ./) failed due to a wrong check for `./scripts/start.sh`. This is not fixed.
* Now checks if the apps directory contains sub directories before accessing `apps/*/`. The latter throws an error for the case there is no sub directory and stopping runtipi fails.
* Added missing `.sh` in 'please run as root' note.
=> Fixing minor issues in start and stop scripts

scripts/start.sh
Offers option to choose between network interfaces for the case multiple defaults were found
Looks like this:
1. Prints available default network interfaces
2. Prompt to choose between interfaces
3. Error handling for not existing interfaces
4. Overwrites the existing variable `NETWORK_INTERFACE` --> Everything after follows the process as intended
Also handles the very unlikely case of 0 available default network interfaces.
Fixes https://github.com/meienberger/runtipi/issues/210
=> start.sh - choose between network interfaces

.github/workflows/ci.yml, docker-compose.dev.yml, docker-compose.rc.yml, docker-compose.yml
Use postgres:14 instead of postgres:latest (which resolves to postgres:15) because of a database version incompatibility error. This resolves #242 so master works again, however a better fix would be to upgrade from postgres 14 to 15.
Also, I made this change in the GitHub Workflow but I'm not sure if this is necessary or wanted.
=> fix: Use postgres:14 instead of postgres:latest 

README.md, scripts/configure.sh, scripts/install.sh, scripts/start.sh, scripts/system.sh, templates/config-sample.json
Add the possibility to install Tipi using just one curl command.
```
curl -L https://setup.runtipi.com | bash
```
This will provide an easier installation/update flow by avoiding using `git clone` and `git pull`
- New `install.sh` script which downloads the latest version and replace the files.
- Update `system.sh` to download latest install script from github and to create a backup of the previous config in case of failure
- Remove the update docker on each start in configure script
- Update README
=> feat: install through bash script

README.md
Changed demo.runtipi.com to https://demo.runtipi.com
=> Updated demo instance link [skip ci]

.devcontainer/devcontainer.json, .devcontainer/filewatcher.sh, .devcontainer/postCreateCommand.sh, package.json
With this PR you can start Tipi in GitHub Codespaces (aka. devcontainers). You don’t need to install dependencies in it. GitHub gives you [60 hours](https://github.blog/changelog/2022-11-09-codespaces-for-free-and-pro-accounts/) of run time for a 2 core codespace, plus 15 GB of storage to use each month for free.
> Should be a new heading in Running for development
> 
The easiest way to start developing on Tipi is to use GitHub Codespaces. All dependency are already installed, you don’t need to set up anything extra. But there are a few things to consider developing in Codespaces. 
After the Codespaces is created, and you are faced with the IDE, you can start Tipi with `npm run start:dev-container`. This is necessary because we have to start an extra script to handle permissions inside …
=> Adding config for codespaces [skip ci]

packages/dashboard/src/server/context.ts, packages/dashboard/src/server/routers/auth/auth.router.ts, packages/dashboard/src/server/services/auth/auth.service.test.ts, packages/dashboard/src/server/services/auth/auth.service.ts
No need to use Prisma from context, as it can be simply imported in service files. This simplifies code and tests
=> refactor: remove prisma from context and use client directly in service

packages/dashboard/package.json, packages/dashboard/src/client/mocks/fixtures/app.fixtures.ts, packages/dashboard/src/client/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.test.tsx, packages/dashboard/src/client/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.tsx, packages/dashboard/src/client/modules/Apps/pages/AppsPage/AppsPage.tsx, packages/dashboard/src/server/services/apps/apps.helpers.test.ts, packages/dashboard/src/server/services/apps/apps.helpers.ts, packages/dashboard/src/server/services/apps/apps.service.test.ts, packages/dashboard/src/server/services/apps/apps.service.ts, pnpm-lock.yaml
There is a bug in which the client is not receiving the update info correctly. The info is always taken from the installed app files.
- Add two new fields `latestVersion` and `latestDockerVersion` to the app
- Change frontend to use those fields instead of app info
- Increase test coverage for apps service
=> fix: client not showing latest app updates 

scripts/app.sh
Relates to #311 
I create a docker-compose in the runtipi folder that mounts my `/cellar` volume:
```
version: "3.7"
services:
filebrowser:
volumes:
- /cellar:/srv/cellar
```
Filebrowser gets the volume:
```
PS ❯ $fb = docker inspect filebrowser | ConvertFrom-Json; $fb.Mounts | ft
Type   Source                                                                                         Destination   Mode   RW Propagation
----   ------                                                                                         -----------   ----   -- -----------
bind   /usr/bin/runtipi/app-data/filebrowser/data/db                                                  /database     rw   True rprivate
bind   /usr/bin/runtipi/app-data …
```
=> User persistent docker-compose files

src/client/modules/AppStore/helpers/__tests__/table.helpers.test.ts, src/client/modules/AppStore/helpers/table.helpers.ts, src/client/modules/Apps/pages/AppDetailsPage/AppDetailsPage.test.tsx, src/client/modules/Apps/pages/AppDetailsPage/AppDetailsPage.tsx, src/pages/app-store/[id].tsx, src/pages/apps/[id].tsx, src/server/tests/apps.factory.ts
This PR fixes a bug where the breadcrumbs were displayed wrongly in the app-store. Whenever you came from the app store or from the my apps page, it would always be `/apps/...`
- Added props `refSlug` and `refTitle` in `AppDetailsPage` component
- Pass these props accordingly in bot app-store and apps
=> fix(app-store): incorrect breadcrumbs displayed in app store

scripts/app.sh
This Pull Request addresses #334
If some apps are not stopped correctly (or manually) before starting Tipi again, users will receive an error about the network.
- Added the `--force-recreate` option in both update and start in order to force the container to re-create instead of trying to start in its previous state
=> fix(app.sh): force recreate containers on start

scripts/app.sh, scripts/start-dev.sh, scripts/start.sh, src/client/modules/Settings/components/SettingsForm/SettingsForm.tsx, src/server/core/TipiConfig/TipiConfig.test.ts, src/server/core/TipiConfig/TipiConfig.ts, src/server/services/system/system.service.test.ts, src/server/services/system/system.service.ts, templates/env-sample
There is a bug when the user specifies an empty `storagePath` in their `settings.json` file (or through the new form in the dashboard)
- Ensure the `storagePath` can never be saved as an empty string in the `settingsSchema` by trimming the value and returning undefined if the string is empty
- Add a check in the `start.sh` script to not replace the default `storagePath` if it is an empty string.
- Added a demo mode cli option to avoid users changing the config in the demo instance
=> fix: empty storage path error

src/client/components/ui/Switch/Switch.module.scss, src/client/components/ui/Switch/Switch.test.tsx, src/client/components/ui/Switch/Switch.tsx, src/client/modules/Apps/components/InstallForm/InstallForm.tsx
Replace the non-accessible `Switch` component with [radix-ui](https://www.radix-ui.com/) `Switch` primitive
- Refactor `Switch` UI component using radix-ui
- Replace all usages of legacy `Switch` component
- Refactor tests to use accessible elements
=> refactor: switch component using radix

src/client/mocks/handlers.ts, src/client/modules/Settings/containers/GeneralActions/GeneralActions.test.tsx, src/client/modules/Settings/containers/GeneralActions/GeneralActions.tsx, src/server/services/system/system.service.test.ts, src/server/services/system/system.service.ts
This PR adds the ability to view the GitHub release notes on the dashboard before updating.
=>  feat: display update release notes

src/client/core/constants.ts, src/client/modules/AppStore/components/CategorySelector/CategorySelecte.test.tsx, src/client/modules/AppStore/components/CategorySelector/CategorySelector.tsx, src/client/modules/AppStore/helpers/table.helpers.ts, src/server/services/apps/apps.types.ts
This PR adds an icon for each category available and displays this icon in the dropdown selector from the dashboard
- Add a [tabler-icon](https://tabler-icons.io/) for each category in `constants.ts`
- Customize render options of the `CategorySelect.tsx` to display the icon
- Add new category "AI"
=> style: add an icon for each category in the dropdown select

.github/workflows/ci.yml, __mocks__/redis.ts, docker-compose.dev.yml, docker-compose.rc.yml, docker-compose.test.yml, docker-compose.yml, src/server/core/TipiCache/TipiCache.ts
Sometimes, the Redis instance is not yet ready and the client is starting anyways causing issues in the dashboard. This PR adds a `healthcheck` in the docker-compose file in order to start the dashboard only when Redis is healthy
- Added a `healthcheck` for Redis in all `docker-compose.yml`
- Added error logs for Redis
=> feat: redis healthcheck

src/client/modules/Apps/components/AppDetailsTabs.tsx
Add a new section to display the app website in the "Base info" tab
=> feat: add app website info in details tab

src/server/services/system/system.service.test.ts, src/server/services/system/system.service.ts
On some operating systems, or under special conditions, the script `system-info.sh` fails to create the json. This causes the UI to show an error that can be avoided using default values. The user would still understand there is an issue with the script but the UX will be better by not showing an error as the opening page of the dashboard.
=> fix: return default values of 0 when system-info.json fails to parse

src/client/mocks/fixtures/app.fixtures.ts, src/client/modules/Apps/components/InstallForm/InstallForm.test.tsx, src/client/modules/Apps/components/InstallForm/InstallForm.tsx, src/client/modules/Apps/components/InstallModal/InstallModal.tsx, src/client/modules/Apps/components/UpdateSettingsModal.tsx, src/server/services/apps/apps.helpers.ts, src/server/services/apps/apps.service.test.ts, src/server/services/apps/apps.service.ts, src/server/tests/apps.factory.ts
Allow app developers to force exposure through a domain. Some apps cannot work without a domain and SSL certificate, this PR adds the ability to specify it with a flag `force_expose` in the config of the app
=> feat: force expose apps

.eslintrc.js, __mocks__/fs-extra.ts, package.json, pnpm-lock.yaml, src/client/mocks/fixtures/app.fixtures.ts, src/server/services/apps/apps.helpers.test.ts, src/server/services/apps/apps.helpers.ts, src/server/tests/apps.factory.ts, src/server/utils/env-generation.ts
Some apps require a [Vapid](https://datatracker.ietf.org/doc/html/draft-thomson-webpush-vapid) key pair to manage push notifications.
Added a new option in `config.json`: `generate_vapid_keys`. If set to true, both `VAPID_PUBLIC_KEY` and `VAPID_PRIVATE_KEY` will be populated and available as environment variables
=> feat: auto-generate app vapid key pair

src/client/components/AppStatus/AppStatus.tsx, src/client/components/AppTile/AppTile.tsx, src/client/messages/en.json, src/client/modules/Apps/components/AppActions/AppActions.tsx, src/client/modules/Apps/components/InstallForm/InstallForm.tsx, src/client/modules/Apps/components/InstallModal/InstallModal.tsx, src/client/modules/Apps/components/StopModal.tsx, src/client/modules/Apps/components/UninstallModal.tsx, src/client/modules/Apps/components/UpdateModal/UpdateModal.tsx, src/client/modules/Apps/components/UpdateSettingsModal.tsx, src/client/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.test.tsx, src/client/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.tsx, src/client/modules/Apps/pages/AppDetailsPage/AppDetailsPage.tsx, src/client/modules/Apps/pages/AppsPage/AppsPage.tsx, src/client/modules/Apps/utils/validators/validators.ts, src/client/state/uiStore.ts, src/client/utils/page-helpers.ts
This PR adds all the translation strings for the "My Apps" flow with app details, forms, and actions
=> feat: add translations strings for my-apps page

src/client/core/constants.ts, src/client/messages/en.json, src/client/modules/AppStore/components/AppStoreTile/AppStoreTile.tsx, src/client/modules/AppStore/components/CategorySelector/CategorySelector.tsx, src/client/modules/AppStore/pages/AppStorePage/AppStorePage.tsx, src/client/modules/Apps/components/AppDetailsTabs.tsx, src/client/modules/Settings/components/ChangePasswordForm/ChangePasswordForm.test.tsx, src/client/modules/Settings/components/ChangePasswordForm/ChangePasswordForm.tsx, src/client/modules/Settings/components/OtpForm/OptForm.test.tsx, src/client/modules/Settings/components/OtpForm/OtpForm.tsx, src/client/modules/Settings/components/SettingsForm/SettingsForm.tsx, src/client/modules/Settings/containers/GeneralActions/GeneralActions.tsx, src/client/modules/Settings/containers/SecurityContainer/SecurityContainer.tsx, src/client/modules/Settings/containers/SettingsContainer/SettingsContainer.tsx, src/client/modules/Settings/pages/SettingsPage/SettingsPage.tsx, src/client/state/uiStore.ts, src/client/utils/page-helpers.ts, src/pages/_app.tsx, src/server/services/system/system.service.test.ts, src/server/services/system/system.service.ts
Localise the latest parts of the app (Settings and App Store)
=> feat: localise app-store and settings

traefik/dynamic/dynamic.yml, traefik/traefik.yml
Gives Traefik the possibility to have a dynamic config. Worked with mastodon but did not interfere with any other apps
=> Enable Traefik Dynamic Configs via File

src/server/services/apps/apps.helpers.test.ts, src/server/services/apps/apps.helpers.ts
It is currently impossible to install an app with a boolean value set to `false` if that field is required. This PR solves the issue by checking for the field type before throwing an error
=> fix(apps.helpers): make required boolean field pass with false value

.github/workflows/e2e.yml, __mocks__/fs-extra.ts, scripts/app.sh, src/server/services/apps/apps.helpers.ts, src/server/services/apps/apps.service.test.ts, src/server/services/apps/apps.service.ts
As a developer, I need to be able to use my app environment variables in any data file and not only `docker-compose.yml`
- Copy data folder from node instead of the bash script
- Recursively look for files with the extension `.template` and replace `{{VALUES}}` with available environment variables
=> feat: allow variable replacement in data files

src/client/components/ui/EmptyPage/EmptyPage.tsx, src/client/modules/Dashboard/components/SystemStat.tsx, src/client/modules/Dashboard/containers/DashboardContainer.tsx, src/client/modules/Dashboard/pages/DashboardPage/DashboardPage.tsx
In order to avoid a flashing of no content on first page load, a loading state has been added to the dashboard page.
=> feat: add loading state to dashboard page

scripts/configure.sh
When installing packages, if `pacman` doesn't find a package in any of `pacman`'s repositories, try installing the package from the AUR using `yay`.
On Arch Linux, some packages are not available through the `pacman` package manager (I'm looking at you, `fswatch`). Thus we should try to install it from the AUR using the `yay` AUR helper, and if `yay` is not found (there are other AUR helpers, yay is just the most common) alert the user to try to install the offending package manually.
=> Modify configure.sh to try using an AUR helper

pnpm-lock.yaml, src/server/core/TipiConfig/TipiConfig.ts, src/server/routers/system/system.router.ts
When a setting is not used by the app (eg, port), it gets overridden when saving settings. Because the Zod schema doesn't allow it.
Add all non-functional settings to the setting schema to not delete those when saving settings
=> fix: settings like port getting deleted on save 

packages/cli/src/executors/repo/repo.executors.ts
A bug can happen to some user where git is signaling that the repo is not safe to pull. 
```
fatal: detected dubious ownership in repository at 
```
This PR adds an exception to the cloned repo
=> fix(cli): mark app store repo as git safe folder before pulling

package.json, packages/cli/.env.test, packages/cli/src/executors/app/app.executors.ts, packages/cli/src/executors/app/app.helpers.ts, packages/cli/src/executors/repo/repo.executors.ts, packages/cli/src/executors/system/system.executors.ts, packages/cli/src/executors/system/system.helpers.ts, packages/cli/src/services/watcher/watcher.ts, scripts/install.sh, src/server/common/session.helpers.ts
Since we are not running as root anymore, some containers needs to be forced into a user:group couple. This PR introduces a new system to generate a `tipi` group on startup and assign it to the current user aswell as exposing the env variables `TIPI_UID` and `TIPI_GID`
=> fix: app files permissions

scripts/install.sh
The previous curl command in install.sh was failing due to a permanent redirect on the GitHub API endpoint. This error was manifesting as a "Moved Permanently" message when attempting to fetch the latest release version. By adding the -L flag to the curl command, the script now correctly follows the redirect to the new URL, ensuring the latest version information is accurately retrieved. This change resolves the error and ensures the installation script operates reliably.
=> Add -L flag to curl command to follow redirects in install.sh

packages/cli/src/executors/app/app.executors.ts, packages/cli/src/index.ts
In order to perform maintenance with apps. The commands `stop` and `start` have been added to the runtipi cli.
- `./runtipi-cli app start nextcloud`
- `./runtipi-cli app stop nextcloud`
=> feat(cli): add commands for starting and stopping apps

packages/cli/src/executors/app/app.helpers.ts
During app.env generation, `APP_PROTOCOL` is generated only if the protocol is https. Some apps require the use of this variable in templates thus requiring a value when http
=> chore(cli): generate APP_PROTOCOL env var even for http

src/app/(dashboard)/app-store/components/AppStoreTable/AppStoreTable.tsx, src/app/(dashboard)/app-store/page.tsx
Missing empty page text when filtering app-store close #795
=> fix(app-store): show a text when there is no filtering result

src/app/not-found.tsx
This PR moves the 404 page to the new app directory and `not-found.tsx` pattern. Closes #754
=> refactor: move 404 page to RSC

src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
Fix a small css issue which was causing the description of an app to be centered where it should have been aligned on the left. Closes #761
=> fix(app-details): align description text left when md or larger

package.json, pnpm-lock.yaml, src/app/(dashboard)/app-store/[id]/components/InstallModal/InstallModal.tsx, src/app/(dashboard)/app-store/[id]/components/UpdateSettingsModal/UpdateSettingsModal.tsx, src/client/components/ui/ScrollArea/ScrollArea.module.css, src/client/components/ui/ScrollArea/ScrollArea.tsx, src/client/components/ui/ScrollArea/index.ts
Sometimes if the app has many field required to be filled by the user, the install form would go off screen and making it hard for the user to reach the end. This PR adds a new `ScrollArea` component based on radix-ui's primitive. The height of the modal content will be capped at 500px and be scrollable after that.
Closes #770
=> Make install form scrollable

packages/cli/assets/docker-compose.yml, packages/cli/src/executors/system/system.helpers.ts, packages/shared/src/schemas/env-schemas.ts
Update the cli part to be able to take an extra config option: ```postgresPort``` for changing the port that postgres will listen to. Issue here: https://github.com/runtipi/runtipi/issues/897
=> feat(cli): set custom postgres port in config.json

docker-compose.prod.yml, packages/cli/assets/docker-compose.yml, packages/worker/Dockerfile, packages/worker/Dockerfile.dev, packages/worker/src/lib/docker/docker-helpers.test.ts, packages/worker/src/lib/docker/docker-helpers.ts
In an attempt to reduce the size of the worker image, it was discovered that downloading the docker cli binary directly instead of adding it through the package manager resulted in a half-size image. Thank you @steveiliop56 for your precious help on this one
=> refactor: download docker compose binary

src/client/messages/en.json
The current update prompt is not accurate anymore. So migrating to a simpler info that is easier to understand.
=> fix(app-update): change update confirmation text

packages/worker/src/services/repo/repo.executors.ts, packages/worker/src/services/repo/repo.helpers.ts
This pull request addresses a limitation with runtipi [Application Repository](https://runtipi.io/docs/apps-available) custom repo URLs as it is restricted to using only the master branch. This restriction forced developers of new apps definition to either manually update the repository branch on the runtipi server filesystem or [merge unfinished work into their main branch](https://giphy.com/clips/theoffice-lkibHaGO1xmJXapEdq).
This pull request addresses this by allowing people to specify an optional branch along with the Git repository URL, enabling them to work on projects without affecting their main branch. 
We can now use the following syntax:
- https://github.com/foobar/runtipi-appstore
- https://github.com/foobar/runtipi-appstore/tree/renovate/n8nio-n8n-1.x
The code modifications …
=> feat(support-repoURL-with-branch-syntax): If a appstore repo URL contains a branch, checkout that branch

docker-compose.dev.yml
Sometimes during development, the dashboard crashes, so with this policy it will restart automaticallyl.
=> feat(dev): restart dashboard unless-stopped

scripts/install.sh
The OS detection in the install script relies on finding and reading files in `/etc` related to the OS version.
The regex currently used has no protection against directories, so if a directory matching the regex is encountered, the installer will try to `cat` it and fail. This problem can be observed on Linux Mint where an `upstream-release/` directory is present and the installer fails with:
```
cat /etc/upstream-release: Is a directory
```
This PR aims to update the regex used to only read files.
=> Update regex in install script
