runtipi/runtipi

- ansible/host_vars/tipi.yml
- ansible/tasks/common/docker.yml
- ansible/tasks/common/essential.yml
- ansible/tasks/common/packages.yml
- apps/filerun/config.json
- apps/freshrss/docker-compose.yml
- apps/invidious/docker-compose.arm.yml
- apps/pihole/docker-compose.yml
- packages/system-api/package.json
- packages/system-api/src/modules/apps/__tests__/apps.service.test.ts
- packages/system-api/src/server.ts
- pnpm-lock.yaml
- scripts/app.sh
- scripts/start.sh
- templates/env-api-sample
- templates/env-sample
Add conditional statement to support multiple docker-compose.yml files depending on the Architecture.
Will allow to add apps only for specific archs in the future.
> Support different architectures for apps

- README.md
- apps/filebrowser/docker-compose.yml
- scripts/configure.sh
- scripts/start.sh
- scripts/stop.sh
Since the dockerization of the backend, the user is already root in the container and can handle update without prior permissions
- Update scripts to remove user id requirements
> Remove requirement for being user id 1000

- README.md
- apps/adguard/config.json
- apps/adguard/data/conf/AdGuardHome.yaml
- apps/adguard/docker-compose.yml
> Add Adguard Home #31

- apps/libreddit/config.json
- apps/libreddit/docker-compose.yml
> Add LibReddit App

- apps/nitter/config.json
- apps/nitter/data/nitter.conf
- apps/nitter/docker-compose.yml
> Add Nitter App

- apps/vaultwarden/config.json
- apps/vaultwarden/docker-compose.yml
> Add Vaultwarden App

- apps/prowlarr/config.json
- apps/prowlarr/docker-compose.yml
Adds Prowlarr, a (better) alternative to Jackett, to the stack
> Add Prowlarr

- apps/jackett/docker-compose.yml
- apps/jellyfin/docker-compose.yml
- apps/radarr/docker-compose.yml
- apps/sonarr/docker-compose.yml
- apps/transmission/docker-compose.yml
Several of the file paths were somewhat messy, so I've gone ahead and updated them to match with TRaSH's guide (https://trash-guides.info). This should make it simpler for users to understand.
I have several apps lined up to add to the project, so the sooner this gets merged the sooner I can add those!
> Update paths to follow TRaSH's guide

- README.md
- apps/tautulli/config.json
- apps/tautulli/docker-compose.yml
Adds Tautulli (https://github.com/Tautulli/Tautulli) to the list of apps
> Add Tautulli

- apps/photoprism/config.json
- apps/photoprism/docker-compose.yml
Added Photoprism as requested in #59 
Tested on Debian 11 proxmox enviroment
> Add Photoprism

- apps/nodered/config.json
- apps/nodered/data/settings.js
- apps/nodered/docker-compose.yml
Added node red requested in #87 
Tested on Debian 11 on a proxmox host.
> Added Node-RED

- apps/mealie/config.json
- apps/mealie/docker-compose.yml
- apps/mealie/metadata/description.md
> [APP] Mealie

- apps/mealie/config.json
- apps/mealie/docker-compose.yml
Added Mealie as requested in #93
> Add Mealie

- scripts/start.sh
Fix install script for Arch #122
> Fix Timezone detection for Arch

- packages/dashboard/src/generated/graphql.tsx
- packages/dashboard/src/graphql/queries/getApp.graphql
- packages/dashboard/src/graphql/queries/installedApps.graphql
- packages/dashboard/src/graphql/queries/listApps.graphql
- packages/dashboard/src/modules/Apps/containers/AppDetails.tsx
- packages/system-api/src/modules/apps/apps.types.ts
Some apps like portainer require the https protocol to open then. New config option to allow setting
the https protocol
> feat(apps): allow https protocol

- README.md
Added a link to the runtipi appstore inside of the apps list, this allows for people to find it more easily as right now I had to go to the issues page to find the appstore.
> Slight update to Readme.md

- packages/dashboard/src/components/Layout/UpdateBanner.tsx
> Fix typo in UpdateBanner.tsx [skip ci]

- packages/dashboard/src/components/AppStatus/AppStatus.module.scss
- packages/dashboard/src/components/Layout/Layout.tsx
- packages/dashboard/src/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.tsx
Add a link to open exposed app directly using the domain
> feat: add link to open exposed app to domain

- packages/dashboard/src/server/routers/auth/auth.router.ts
- packages/dashboard/src/server/routers/system/system.router.ts
- packages/dashboard/src/server/services/auth/auth.service.test.ts
- packages/dashboard/src/server/services/auth/auth.service.ts
- packages/dashboard/src/server/services/system/index.ts
- packages/dashboard/src/server/services/system/system.service.test.ts
- packages/dashboard/src/server/services/system/system.service.ts
- packages/dashboard/src/server/tests/user.factory.ts
Move auth and system services to class based
> refactor(server): move auth and system services to class

- scripts/start.sh
As mentioned by @fsackur in #308 we shouldn't ask which network interface to use if there is already an internal IP provided by the user
- Put the check for network interface after parsing CLI args and settings.json and run it only if there is no INTERNAL_IP (Closes #308 #309)
- Also check for potential multiple ip for one interface (Closes #298 #289)
> fix(start.sh): don't ask network interface if ip is already set

- scripts/install.sh
Update install.sh to include a Rom Folder.
> Make Rom Folder in the Media Section [skip ci]

- package.json
- pnpm-lock.yaml
- src/client/components/AppStatus/AppStatus.tsx
- src/client/components/AppTile/AppTile.tsx
- src/client/components/Layout/Layout.tsx
- src/client/components/ui/Header/Header.test.tsx
- src/client/components/ui/Header/Header.tsx
- src/pages/_app.tsx
Update `react-tooltip` from v4 to v5 and migrate usages
> refactor: upgrade react tooltip to v5

- src/client/components/ui/Header/Header.tsx
- src/client/components/ui/NavBar/NavBar.tsx
- src/client/messages/en.json
- src/client/modules/Dashboard/containers/DashboardContainer.tsx
- src/client/modules/Dashboard/pages/DashboardPage/DashboardPage.tsx
Use translation keys for the dashboard and header
> feat: translate dashboard and header

- src/client/messages/en.json
- src/client/mocks/getTrpcMock.ts
- src/client/modules/Apps/containers/AppDetailsContainer/AppDetailsContainer.tsx
- src/client/modules/Apps/pages/AppDetailsPage/AppDetailsPage.tsx
- src/client/modules/Apps/pages/AppsPage/AppsPage.tsx
- src/client/modules/Auth/containers/LoginContainer/LoginContainer.tsx
- src/client/modules/Auth/containers/RegisterContainer/RegisterContainer.tsx
- src/client/modules/Auth/containers/ResetPasswordContainer/ResetPasswordContainer.tsx
- src/client/modules/Dashboard/pages/DashboardPage/DashboardPage.tsx
- src/server/services/apps/apps.service.test.ts
- src/server/services/apps/apps.service.ts
- src/server/trpc.ts
- src/server/utils/errors.ts
Add server error messages to the apps.service
> feat: apps server errors

- src/client/components/LanguageSelector/LanguageSelector.tsx
- src/client/components/LanguageSelector/index.ts
- src/client/hooks/__tests__/useLocale.test.ts
- src/client/hooks/useLocale.ts
- src/client/messages/en.json
- src/client/modules/Auth/components/AuthFormLayout/AuthFormLayout.tsx
- src/client/modules/Settings/components/SettingsForm/SettingsForm.tsx
- src/client/utils/page-helpers.ts
- src/shared/internationalization/locales.ts
Add language setting in settings panel and language selector on auth pages
> feat: add language selector settings

- e2e/0004-user-settings.spec.ts
- src/client/components/LanguageSelector/LanguageSelector.tsx
- src/client/components/ui/Select/Select.tsx
Add E2E test suites for user settings
- Password change
- Language change
> test: add e2e suite for change password and language selector

- traefik/traefik.yml
Required for Owncast App PR https://github.com/meienberger/runtipi-appstore/pull/826
Should not affect the deployment of any other Apps
> Enable TLS and Attach to Traefik CertResolver

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- e2e/helpers/db.ts
This PR fixes a bug in the E2E test suite where the wrong postgres password was used to connect remotely to the db.
> ci: fix e2e postgres connexion

- .github/workflows/beta-release.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
In order to release the new version 1.6.0 the release workflow needs to be adapted to the new changes done for 1.6.0
> ci: create new `release` workflow

- package.json
- packages/cli/package.json
- packages/cli/src/executors/app/app.executors.ts
- packages/cli/src/executors/repo/repo.executors.ts
- packages/cli/src/executors/system/system.executors.ts
- packages/cli/src/index.ts
- packages/cli/src/services/watcher/watcher.ts
- packages/cli/src/utils/environment/user.ts
This PR is a hotfix for 1.6.0. We tried to release a rootless experience with this new version, unfortunately, users are still facing many issues with permissions on different folders. We are rolling back this feature and will work more on it for a next release.
> Hotfix: Make running as root a hard requirement

- package.json
- packages/cli/src/executors/app/app.executors.ts
- packages/cli/src/executors/repo/repo.executors.ts
- packages/cli/src/executors/system/system.executors.ts
- packages/cli/src/index.ts
- packages/cli/src/utils/environment/environment.ts
- pnpm-lock.yaml
- src/client/components/Markdown/Markdown.tsx
- tests/client/jest.setup.tsx
Now that we don't have a custom server anymore, we need to start all apps somehow. This PR adds this action in the CLI when starting tipi
> feat: start apps on launch

- packages/cli/src/executors/app/app.executors.ts
> Always pull image on app start

- src/app/components/ClientProviders/ThemeProvider/ThemeProvider.tsx
- src/client/state/uiStore.ts
> fix(theme): detect system theme when theme cookie is not present

- packages/cli/src/executors/system/system.executors.ts
- packages/cli/src/services/watcher/watcher.ts
- packages/cli/src/utils/logger/file-logger.ts
- packages/shared/src/utils/logger/Logger.ts
> chore(cli): flush all logs when app is starting

- packages/cli/src/executors/app/app.executors.ts
- packages/cli/src/executors/system/system.executors.ts
- packages/cli/src/index.ts
This PR improves the help messages from the CLI to include examples. Close #824
> refactor: improve cli help

- docker-compose.dev.yml
- docker-compose.prod.yml
- packages/cli/assets/docker-compose.yml
- packages/worker/src/services/system/system.executors.ts
From my small testing in ubuntu 22.04 in wsl and bare metal debian 12 this fix seems to make the disk usage work.
> fix(worker): disk usage fix

- pnpm-lock.yaml
- src/server/services/apps/apps.service.test.ts
- src/server/services/apps/apps.service.ts
> feat(update app): back to prev status before update

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
So I saw in the project kanban, @meienberger had an issue to move from inter to geist. Since it is something extremely easy to implement I changed it although the difference is barely noticeable...
> refactor(ui): change font to geist

- src/app/actions/app-actions/install-app-action.ts
- src/app/actions/app-actions/reset-app-action.ts
- src/app/actions/app-actions/start-app-action.ts
- src/app/actions/app-actions/stop-app-action.ts
- src/app/actions/app-actions/uninstall-app-action.ts
- src/app/actions/app-actions/update-app-action.ts
- src/app/actions/app-actions/update-app-config-action.ts
- src/app/actions/cancel-reset-password/cancel-reset-password-action.ts
- src/app/actions/reset-password/reset-password-action.ts
- src/app/actions/settings/change-password.ts
- src/app/actions/settings/change-username.ts
- src/app/actions/settings/disable-totp.ts
- src/app/actions/settings/get-totp-uri.ts
- src/app/actions/settings/setup-totp-action.ts
- src/app/actions/settings/update-settings.ts
- src/app/actions/utils/ensure-user.ts
> refactor(actions): secure app actions with ensure user util

- README.md
> Revert "chore: fix contributors badge on readme"

- pnpm-lock.yaml
Waiting for https://github.com/dependabot/dependabot-core/issues/9522 before upgrading
> chore: downgrade to pnpm v8
